export {default as HomeLayout} from './HomeLayout'
export {default as Register} from './Register'
export {default as Error} from './Error'
export {default as Login} from './Login'
export {default as Dashboard} from './dashboard'
export {default as Contact} from './Contact'
export {default as About} from './About'
